on:
  push:
    branches:
      - main
name: Zillow Guesser CI/CD
permissions:
  contents: write
jobs:
  unit:
    name: Unit and Widget Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'dev'
      - run: dart tool/env.dart
      - run: flutter pub get
      - run: flutter test --coverage

  web:
    name: Build website
    runs-on: ubuntu-latest
    needs: [unit]
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'dev'
      - run: dart tool/env.dart
      - run: flutter config --enable-web
      - run: flutter build web -t ./lib/main.dart
      - uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          branch: gh-pages
          folder: build/web
