on:
  push:
    branches:
      - main
name: Zillow Guesser CI/CD
jobs:
  unit:
    name: Unit and Widget Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'dev'
      - run: dart tool/env.dart
      - run: flutter pub get
      - run: flutter test --coverage

  web:
    name: Build website
    runs-on: ubuntu-latest
    needs: [unit]
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'dev'
      - run: dart tool/env.dart
      - run: flutter config --enable-web
      - run: flutter build web -t ./lib/Pages/main.dart
      - uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          BASE_BRANCH: main
          BRANCH: gh-pages
          FOLDER: build/web